### ISSUE TITLE
Turbo is still caching the chart - even when setting `turbo-cache-control` to `no-cache`

### ISSUE THREAD

**Issue by tamersalama** [railsjazz/rails_charts#12] opened 2023-04-11 00:58 UTC
I believe I've done everything possible to disable cache on the page where the chart renders, however, chart values are still 'sticky'. I get chart rendered for unintended values.

**Comment by igorkasyanchuk** [comment] 2023-04-11 08:47
@tamersalama as before please try to fork and fix yourself. Maybe even creating a dummy app with this issue can be helpful, so anyone can reproduce the issue.

**Comment by manastyretskyi** [comment] 2023-04-11 08:51
Yes, having at least dummy app where this reproduces would be helpful

**Comment by manastyretskyi** [comment] 2023-11-17 20:43
Going to close this issue for now. Feel free to add new comments or open new issue if the problem is still present.

**Closed by manastyretskyi** 2023-11-17 20:43 UTC
